import type { Aop, AopProducer } from "./types";

// 生産者の購入リンク(アフィリエイト)生成。生産者名からECサイトの検索結果URLを
// 自動生成し、アフィリエイトIDが設定されていれば計測用URLでラップする。
// UI(AopDetailPanel)とMCP(get_aop)の両方から使う。
//
// このモジュールはクライアント(AopDetailPanel)からも読み込まれるため、
// cloudflare:workers の env を直接参照しない。アフィリエイトIDは呼び出し側が
// AffiliateConfig として渡す(サーバーは env から読み、UIは server fn 経由で受け取る)。

/**
 * アフィリエイトID。リンクURLに含まれる公開情報だが、環境ごとに切り替えられる
 * よう環境変数から供給する。未設定(空)なら素の検索URLを返す(リンクは機能する)。
 */
export interface AffiliateConfig {
	/** 楽天アフィリエイトID (例: "0a1b2c3d.e4f5a6b7.0a1b2c3d.e4f5a6b8") */
	rakuten?: string;
	/** もしもアフィリエイトの a_id (Amazon.co.jp プロモーションの広告枠ID) */
	moshimoAmazon?: string;
}

/** ID未設定の既定値。この状態でも素の検索リンクとして機能する */
export const EMPTY_AFFILIATE_CONFIG: AffiliateConfig = {};

/** 楽天市場のジャンルID「ワイン」。検索結果をワインに限定する */
const RAKUTEN_WINE_GENRE_ID = "510915";

// もしもアフィリエイト経由 Amazon.co.jp の固定パラメータ(a_id のみユーザー固有)
const MOSHIMO_AMAZON_PARAMS = "p_id=170&pc_id=185&pl_id=4062";

/**
 * 欧文表記の生産者名 → 日本のECでヒットしやすいカタカナ検索語の共通辞書。
 * 同じ生産者が複数のAOPに登場するため、aops.json 側ではなくここで一元管理する。
 * aops.json の searchKeyword が指定されていればそちらが優先される。
 *
 * **未登録の生産者はラテン文字表記のまま楽天を検索する**ことになり、ほぼヒットしない。
 * 地域単位で「その地域の生産者は全員登録されている」状態を保つ方針(#211)で、
 * data-integrity テストが地域ごとの網羅を固定する(そのための export)。
 */
export const PRODUCER_SEARCH_KEYWORDS: Record<string, string> = {
	// ブルゴーニュ / ボージョレ
	"Domaine Leflaive": "ドメーヌ・ルフレーヴ",
	"Maison Olivier Leflaive": "オリヴィエ・ルフレーヴ",
	"Domaine Ramonet": "ドメーヌ・ラモネ",
	"Domaine de la Romanée-Conti": "ロマネ・コンティ",
	"Domaine Leroy": "ドメーヌ・ルロワ",
	"Domaine d'Auvenay": "ドーヴネ",
	"Domaine Coche-Dury": "コシュ・デュリ",
	"Domaine Georges Roumier": "ジョルジュ・ルーミエ",
	"Domaine Dugat-Py": "デュガ・ピィ",
	"Domaine Cécile Tremblay": "セシル・トランブレイ",
	"Domaine Jean-Marc & Thomas Bouley": "ジャン・マルク・ブーレイ",
	"Domaine Hubert Lamy": "ユベール・ラミー",
	"Maison Louis Jadot": "ルイ・ジャド",
	"Maison Louis Latour": "ルイ・ラトゥール",
	"Maison Joseph Drouhin": "ジョゼフ・ドルーアン",
	"Maison Albert Bichot": "アルベール・ビショー",
	"Georges Duboeuf": "ジョルジュ・デュブッフ",
	// シャンパーニュ
	"Moët & Chandon": "モエ・エ・シャンドン",
	"Veuve Clicquot": "ヴーヴ・クリコ",
	Bollinger: "ボランジェ",
	Taittinger: "テタンジェ",
	Pommery: "ポメリー",
	"Louis Roederer": "ルイ・ロデレール",
	"Laurent-Perrier": "ローラン・ペリエ",
	Ruinart: "ルイナール",
	"Nicolas Feuillatte": "ニコラ・フィアット",
	"Jacques Selosse": "ジャック・セロス",
	Salon: "サロン シャンパーニュ",
	"Krug (Clos d'Ambonnay)": "クリュッグ",
	"Krug (Clos du Mesnil)": "クリュッグ クロ・デュ・メニル",
	Deutz: "ドゥーツ",
	Gosset: "ゴッセ",
	"Billecart-Salmon": "ビルカール・サルモン",
	"Philipponnat (Clos des Goisses)": "フィリポナ",
	// シャンパーニュ(#224 で全生産者ぶんを整備。村ごとの造り手と大手メゾンを通してカタカナ表記を持つ)
	"Pol Roger": "ポル・ロジェ",
	"Charles Heidsieck": "シャルル・エドシック",
	"Piper-Heidsieck": "パイパー・エドシック",
	"Perrier-Jouët": "ペリエ・ジュエ",
	Lanson: "ランソン",
	"Bruno Paillard": "ブリュノ・パイヤール",
	Krug: "クリュッグ",
	Philipponnat: "フィリポナ",
	Jacquesson: "ジャクソン",
	"G.H. Mumm": "マム",
	Ayala: "アヤラ",
	Lallier: "ラリエ",
	"Henri Giraud": "アンリ・ジロー",
	Gatinois: "ガティノワ",
	"Henri Goutorbe": "アンリ・グトルブ",
	"Egly-Ouriet": "エグリ・ウーリエ",
	"Eric Rodez": "エリック・ロデズ",
	"Marie-Noëlle Ledru": "マリー・ノエル・ルドリュ",
	"Paul Déthune": "ポール・デテュンヌ",
	"Agrapart & Fils": "アグラパール",
	"De Sousa": "ド・スーザ",
	"Franck Bonville": "フランク・ボンヴィル",
	"Varnier-Fannière": "ヴァルニエ・ファニエール",
	"Joël Vautier": "ジョエル・ヴォティエ",
	"Paul Bara": "ポール・バラ",
	"Pierre Paillard": "ピエール・パイヤール",
	Barnaut: "バルノー",
	"Benoît Lahaye": "ブノワ・ライエ",
	"André Clouet": "アンドレ・クルエ",
	Brice: "ブリス",
	"R&L Legras": "ルグラ",
	"Vazart-Coquart": "ヴァザール・コカール",
	"Roland Champion": "ロラン・シャンピオン",
	"Legras & Haas": "ルグラ・エ・アース",
	"Diebolt-Vallois": "ディエボル・ヴァロワ",
	"Lilbert-Fils": "リルベール・フィス",
	Bonnaire: "ボネール",
	"Pertois-Lebrun": "ペルトワ・ルブラン",
	"Voirin-Jumel": "ヴォワラン・ジュメル",
	"Sugot-Feneuil": "シュゴ・フヌイユ",
	"Guy de Chassey": "ギィ・ド・シャセイ",
	"Yves Beautrait": "イヴ・ボートレ",
	"Champagne Mailly Grand Cru": "マイィ・グラン・クリュ",
	"Ernest Remy": "エルネスト・レミー",
	Delamotte: "ドゥラモット",
	"Pierre Péters": "ピエール・ペテルス",
	"Robert Moncuit": "ロベール・モンキュイ",
	"Pertois-Moriset": "ペルトワ・モリゼ",
	"Guy Charlemagne": "ギィ・シャルルマーニュ",
	"Launois Père & Fils": "ロノワ",
	"Jean Milan": "ジャン・ミラン",
	"Claude Cazals": "クロード・カザル",
	"Lang-Biemont": "ラング・ビエモン",
	"Legras-Frapart": "ルグラ・フラパール",
	"François Chaumont": "フランソワ・ショーモン",
	"François Secondé": "フランソワ・スコンデ",
	Chauvet: "ショーヴェ",
	Lamiable: "ラミアブル",
	"Michel Arnould": "ミシェル・アルヌー",
	"Hugues Godmé": "ユーグ・ゴドメ",
	"Pehu-Simonet": "ペユ・シモネ",
	"Jacques Rousseaux": "ジャック・ルソー",
	"Etienne Lefevre": "エティエンヌ・ルフェーヴル",
	Cuperly: "キュペルリー",
	"Louis de Sacy": "ルイ・ド・サシー",
	"Fresnet-Juillet": "フレネ・ジュイエ",
	"Juillet-Lallement": "ジュイエ・ラルマン",
	"Yves Ruffin": "イヴ・リュファン",
	"Hubert Billiard": "ユベール・ビヤール",
	"Bertrand Vallois": "ベルトラン・ヴァロワ",
	"Bonnevie-Bocart": "ボヌヴィ・ボカール",
	"Gonet-Médeville": "ゴネ・メドヴィル",
	"Bonnet-Ponson": "ボネ・ポンソン",
	"Bertrand Delespierre": "ベルトラン・ドゥレスピエール",
	"Autréau de Champillon": "オートロー・ド・シャンピヨン",
	Cattier: "カティエ",
	Gardet: "ガルデ",
	"J. Lassalle": "ラサール",
	"J. Dumangin Fils": "デュマンジャン",
	"Jean-Marie Massonnot": "ジャン・マリー・マソノ",
	"Pierre Gimonnet & Fils": "ピエール・ジモネ",
	"Paul Michel": "ポール・ミシェル",
	"Georges Laval": "ジョルジュ・ラヴァル",
	"René Geoffroy": "ルネ・ジョフロワ",
	"Sanchez-Le Guédard": "サンチェス・ル・ゲダール",
	"Gaston Chiquet": "ガストン・シケ",
	Savart: "サヴァール",
	"Nicolas Maillart": "ニコラ・マイヤール",
	"G. Tribaut": "トリボー",
	"Locret-Lachaud": "ロクレ・ラショー",
	"Louis Nicaise": "ルイ・ニケーズ",
	"L. Aubry Fils": "オーブリー",
	"Vincent Perseval": "ヴァンサン・ペルスヴァル",
	"Jacquinet-Dumez": "ジャキネ・デュメ",
	"Canard-Duchêne": "カナール・デュシェーヌ",
	"Ployez-Jacquemart": "プロワイエ・ジャックマール",
	"Bérêche & Fils": "ベレッシュ",
	"Forget-Chemin": "フォルジェ・シュマン",
	"Forget-Brimont": "フォルジェ・ブリモン",
	"Marc Hébrart": "マルク・エブラール",
	"R. Pouillon & Fils": "プイヨン",
	Vollereaux: "ヴォルロー",
	Mandois: "マンドワ",
	"Jean-Marc Sélèque": "ジャン・マルク・セレック",
	"Vilmart & Cie": "ヴィルマール",
	"Hubert Paulet": "ユベール・ポーレ",
	"Marc Chauvet": "マルク・ショーヴェ",
	Dumenil: "デュムニル",
	"Hervieux-Dumez": "エルヴュー・デュメ",
	"Manceaux-Talbot": "マンソー・タルボ",
	"R. Froment & Fils": "フロマン",
	"Georges Vollereaux": "ジョルジュ・ヴォルロー",
	"David Léclapart": "ダヴィッド・レクラパール",
	"Pascal Redon & Fils": "パスカル・ルドン",
	"Baillette-Prudhomme": "バイエット・プリュドム",
	"Cher Potron": "シェール・ポトロン",
	"Larmandier-Bernier": "ラルマンディエ・ベルニエ",
	"Veuve Fourny & Fils": "ヴーヴ・フルニー",
	"Duval-Leroy": "デュヴァル・ルロワ",
	"Guy Larmandier": "ギィ・ラルマンディエ",
	"Pascal Doquet": "パスカル・ドケ",
	"Bergeronneau-Marion": "ベルジュロノー・マリオン",
	Stroebel: "ストレーベル",
	"Sadi Malot": "サディ・マロ",
	"A. Margaine": "マルゲーヌ",
	"Lelarge-Pugeot": "ルラルジュ・ピュジョ",
	"Roger Coulon": "ロジェ・クーロン",
	"Alexandre Bonnet": "アレクサンドル・ボネ",
	"Olivier Horiot": "オリヴィエ・オリオ",
	"Laurenti Père et Fils": "ローランティ",
	"Leguay-Truchon": "ルゲ・トリュション",
	// ボルドー(村名AOCの代表生産者として登場するシャトー)
	Pétrus: "ペトリュス",
	"Château d'Yquem": "シャトー・ディケム",
	"Château Margaux": "シャトー・マルゴー",
	"Château Palmer": "シャトー・パルメ",
	"Château Figeac": "シャトー・フィジャック",
	"Château Angélus": "シャトー・アンジェリュス",
	"Château Pavie": "シャトー・パヴィ",
	"Vieux Château Certan": "ヴィユー・シャトー・セルタン",
	"Château La Gaffelière": "シャトー・ラ・ガフリエール",
	// サンテミリオン格付け(2022年)グラン・クリュ・クラッセ 71件
	"Château Badette": "シャトー・バデット",
	"Château Balestard la Tonnelle": "シャトー・バレスタール・ラ・トネル",
	"Château Barde-Haut": "シャトー・バルド・オー",
	"Château Bellefont Belcier": "シャトー・ベルフォン・ベルシェ",
	"Château Bellevue": "シャトー・ベルヴュー",
	"Château Berliquet": "シャトー・ベルリケ",
	"Château Boutisse": "シャトー・ブティス",
	"Château Cadet-Bon": "シャトー・カデ・ボン",
	"Château Cap de Mourlin": "シャトー・カップ・ド・ムルラン",
	"Château Chauvin": "シャトー・ショーヴァン",
	"Château Clos de Sarpe": "シャトー・クロ・ド・サルプ",
	"Château Corbin": "シャトー・コルバン",
	"Château Corbin Michotte": "シャトー・コルバン・ミショット",
	"Château Croix de Labrie": "シャトー・クロワ・ド・ラブリ",
	"Château Côte de Baleau": "シャトー・コート・ド・バロー",
	"Château Dassault": "シャトー・ダッソー",
	"Château Destieux": "シャトー・デスティユー",
	"Château Faugères": "シャトー・フォジェール",
	"Château Fleur Cardinale": "シャトー・フルール・カルディナル",
	"Château Fombrauge": "シャトー・フォンブロージュ",
	"Château Fonplégade": "シャトー・フォンプレガード",
	"Château Fonroque": "シャトー・フォンロック",
	"Château Franc Mayne": "シャトー・フラン・メーヌ",
	"Château Grand Corbin": "シャトー・グラン・コルバン",
	"Château Grand Corbin-Despagne": "シャトー・グラン・コルバン・デスパーニュ",
	"Château Grand Mayne": "シャトー・グラン・メーヌ",
	"Château Guadet": "シャトー・グアデ",
	"Château Haut-Sarpe": "シャトー・オー・サルプ",
	"Château Jean Faure": "シャトー・ジャン・フォール",
	"Château La Fleur Morange": "シャトー・ラ・フルール・モランジュ",
	"Château Laniote": "シャトー・ラニョット",
	"Château Larmande": "シャトー・ラルマンド",
	"Château Laroque": "シャトー・ラロック",
	"Château Laroze": "シャトー・ラローズ",
	"Château Le Prieuré": "シャトー・ル・プリューレ",
	"Château Mangot": "シャトー・マンゴ",
	"Château Monbousquet": "シャトー・モンブスケ",
	"Château Montlabert": "シャトー・モンラベール",
	"Château Montlisse": "シャトー・モンリス",
	"Château Moulin du Cadet": "シャトー・ムーラン・デュ・カデ",
	"Château Peby Faugères": "シャトー・ペビ・フォジェール",
	"Château Petit Faurie de Soutard": "シャトー・プティ・フォリ・ド・スータール",
	"Château Ripeau": "シャトー・リポー",
	"Château Rochebelle": "シャトー・ロシュベル",
	"Château Rol Valentin": "シャトー・ロル・ヴァランタン",
	"Château Saint-Georges-Cote-Pavie":
		"シャトー・サン・ジョルジュ・コート・パヴィ",
	"Château Sansonnet": "シャトー・サンソネ",
	"Château Soutard": "シャトー・スータール",
	"Château Tour Baladoz": "シャトー・トゥール・バラドス",
	"Château Tour Saint-Christophe": "シャトー・トゥール・サン・クリストフ",
	"Château Villemaurine": "シャトー・ヴィルモーリーヌ",
	"Château Yon-Figeac": "シャトー・ヨン・フィジャック",
	"Château de Ferrand": "シャトー・ド・フェラン",
	"Château de Pressac": "シャトー・ド・プレサック",
	"Château la Commanderie": "シャトー・ラ・コマンドリー",
	"Château la Confession": "シャトー・ラ・コンフェッション",
	"Château la Couspaude": "シャトー・ラ・クスポード",
	"Château la Croizille": "シャトー・ラ・クロワジーユ",
	"Château la Dominique": "シャトー・ラ・ドミニク",
	"Château la Marzelle": "シャトー・ラ・マルゼル",
	"Château la Serre": "シャトー・ラ・セール",
	"Château la Tour Figeac": "シャトー・ラ・トゥール・フィジャック",
	"Château le Chatelet": "シャトー・ル・シャトレ",
	"Clos Badon Thunevin": "クロ・バドン・テュヌヴァン",
	"Clos Dubreuil": "クロ・デュブルイユ",
	"Clos Saint-Julien": "クロ・サン・ジュリアン",
	"Clos Saint-Martin": "クロ・サン・マルタン",
	"Clos de l'Oratoire": "クロ・ド・ロラトワール",
	"Clos des Jacobins": "クロ・デ・ジャコバン",
	"Couvent des Jacobins": "クーヴァン・デ・ジャコバン",
	Lassegue: "ラセーグ",
	// クリュ・ブルジョワ・エクセプショネル(2025年格付け) 14件
	"Château la Cardonne": "シャトー・ラ・カルドンヌ",
	"Château Castera": "シャトー・カステラ",
	"Château Laujac": "シャトー・ロジャック",
	"Château Malescasse": "シャトー・マレスカス",
	"Château de Malleret": "シャトー・ド・マルレ",
	"Château Paloumey": "シャトー・パルメイ",
	"Château Reysson": "シャトー・レイソン",
	"Château du Taillan": "シャトー・デュ・タイヤン",
	"Château Reverdi": "シャトー・ルヴェルディ",
	"Château d'Arsac": "シャトー・ダルサック",
	"Château Mongravey": "シャトー・モングラヴェイ",
	"Château Paveil de Luze": "シャトー・パヴェイユ・ド・リューズ",
	"Château le Crock": "シャトー・ル・クロック",
	"Château Laffitte Carcasset": "シャトー・ラフィット・カルカセ",
	// ポムロールの著名シャトー(格付け制度が無い産地)
	"Château Lafleur": "シャトー・ラフルール",
	"Château Trotanoy": "シャトー・トロタノワ",
	"Château L'Évangile": "シャトー・レヴァンジル",
	"Château La Conseillante": "シャトー・ラ・コンセイヤント",
	"Château La Fleur-Pétrus": "シャトー・ラ・フルール・ペトリュス",
	"Château L'Église-Clinet": "シャトー・レグリーズ・クリネ",
	"Château Clinet": "シャトー・クリネ",
	"Château Hosanna": "シャトー・オザンナ",
	"Château Gazin": "シャトー・ガザン",
	"Château Nenin": "シャトー・ネナン",
	"Château Beauregard": "シャトー・ボールガール",
	"Château Petit-Village": "シャトー・プティ・ヴィラージュ",
	"Château La Pointe": "シャトー・ラ・ポワント",
	"Château Rouget": "シャトー・ルージェ",
	"Château de Sales": "シャトー・ド・サル",
	"Château Latour à Pomerol": "シャトー・ラトゥール・ア・ポムロール",
	// MICHELIN Grapes 2/1/選出（2026 追加）
	"Domaine Denis Mortet": "ドニ・モルテ",
	"Domaine Dujac": "ドメーヌ・デュジャック",
	"Domaine Georges Mugneret-Gibourg": "ミュニュレ・ジブール",
	"Domaine Bruno Clair": "ブリュノ・クレール",
	"Domaine Gérard Mugneret": "ジェラール・ミュニュレ",
	"Domaine Jacques-Frédéric Mugnier": "ミュニエ",
	"Domaine Paul Pillot": "ポール・ピヨ",
	"Domaine Arnaud Ente": "アルノー・アント",
	"Domaine Jean-Claude Bachelet et Fils": "ジャン・クロード・バシュレ",
	"Domaine Benoît Ente": "ブノワ・アンテ",
	"Domaine Benoît Moreau": "ブノワ・モロー",
	"Domaine Lamy-Caillat": "ラミ・カイヤ",
	"Domaine Bonneau du Martray": "ボノー・デュ・マルトレイ",
	"Domaine des Croix": "ドメーヌ・デ・クロワ",
	"Domaine des Comtes Lafon": "コント・ラフォン",
	"Domaine Étienne Sauzet": "エティエンヌ・ソゼ",
	"Domaine Bruno Lorenzon": "ブルーノ・ロレンゾン",
	"Domaine Jean-Marc Vincent": "ジャン・マルク・ヴァンサン",
	"Domaine Vincent Dureuil-Janthial": "デュルイユ・ジャンティアル",
	"Domaine Armand Rousseau": "アルマン・ルソー",
	"Domaine Denis Bachelet": "ドニ・バシュレ",
	"Domaine Claude Dugat": "クロード・デュガ",
	"Domaine Duroché": "デュロシェ",
	"Domaine Joseph Roty": "ジョセフ・ロティ",
	"Domaine Trapet Père et Fils": "ドメーヌ・トラペ",
	"Domaine Comte Georges de Vogüé": "コント・ジョルジュ・ド・ヴォギュエ",
	"Domaine Ghislaine Barthod": "ジスレーヌ・バルト",
	"Domaine Hudelot-Noëllat": "ユドロ・ノエラ",
	"Domaine du Clos de Tart": "クロ・ド・タール",
	"Domaine Louis Boillot et Fils": "ルイ・ボワイヨ",
	"Domaine des Lambrays": "ドメーヌ・デ・ランブレイ",
	"Domaine Arnoux-Lachaux": "アルヌー・ラショー",
	"Domaine Ponsot": "ドメーヌ・ポンソ",
	"Domaine Sylvain Cathiard": "シルヴァン・カティアール",
	"Domaine Méo-Camuzet": "メオ・カミュゼ",
	"Château de la Tour": "シャトー・ド・ラ・トゥール",
	"Domaine Bernard-Bonin": "ベルナール・ボナン",
	"Domaine Faiveley": "フェヴレ",
	"Domaine Henri Germain et Fils": "アンリ・ジェルマン",
	"Domaine Henri Boillot": "アンリ・ボワイヨ",
	"Domaine Roulot": "ドメーヌ・ルーロ",
	"Maison Vincent Girardin": "ヴァンサン・ジラルダン",
	"Domaine Marquis d'Angerville": "マルキ・ダンジェルヴィル",
	"Domaine de Montille": "ドメーヌ・ド・モンティーユ",
	"Domaine Roblet-Monnot": "ロブレ・モノ",
	"Domaine Michel Lafarge": "ミシェル・ラファルジュ",
	"Maison Benjamin Leroux": "バンジャマン・ルルー",
	"Domaine Pierre-Yves Colin-Morey": "ピエール・イヴ・コラン・モレイ",
	"Domaine Marc Colin et Fils": "マルク・コラン",
	"Domaine Henri & Gilles Buisson": "アンリ・エ・ジル・ビュイッソン",
	"Domaine Berthaut-Gerbet": "ベルトー・ジェルベ",
	"Domaine Sylvain Pataille": "シルヴァン・パタイユ",
	"Domaine Charles Audoin": "シャルル・オドワン",
	"Domaine Felettig": "フェレティグ",
	"Domaine Camille Thiriet": "カミーユ・ティリエ",
	"Domaine Benoît Chevallier": "ブノワ・シュヴァリエ",
	"Domaine Fourrier": "ドメーヌ・フーリエ",
	"Domaine Hubert Lignier": "ユベール・リニエ",
	"Domaine Jobard-Morey": "ジョバール・モレ",
	"Domaine Anne Boisson": "アンヌ・ボワソン",
	"Domaine Ballot-Millot": "バロ・ミロ",
	"Domaine Buisson-Charles": "ビュイッソン・シャルル",
	"Domaine Camille & Guillaume Boillot": "カミーユ・エ・ギヨーム・ボワイヨ",
	"Domaine Pierre Boisson": "ピエール・ボワゾン",
	"Domaine Pierre Morey": "ピエール・モレ",
	"Domaine Pierre Girardin": "ピエール・ジラルダン",
	"Domaine Alex Moreau": "アレックス・モロー",
	"Domaine Vincent Dancer": "ヴァンサン・ダンセ",
	"Domaine Jacques Carillon": "ジャック・カリヨン",
	"Domaine Thomas-Collardot": "トマ・コラルド",
	"Maison Bouchard Père & Fils": "ブーシャール・ペール・エ・フィス",
	"Domaine Bachelet-Monnot": "バシュレ・モノ",
	"Domaine Nicolas Perrault": "ニコラ・ペロー",
	"Domaine Alain Gras": "アラン・グラ",
	"Domaine Jean & Gilles Lafouge": "ラフージュ",
	"Domaine Joseph Colin": "ジョセフ・コラン",
	"Domaine Rapet Père & Fils": "ドメーヌ・ラペ",
	"Domaine Pierre Guillemot": "ピエール・ギユモ",
	"Domaine Yvon Clerget": "イヴォン・クレルジェ",
	"Domaine Maxime Cottenceau": "マキシム・コトンソー",
	// ピエモンテ
	Accornero: "アッコルネロ",
	"Angelo Negro": "アンジェロ・ネグロ",
	"Antichi Vigneti di Cantalupo":
		"アンティキ・ヴィニェティ・ディ・カンタルーポ",
	Antoniolo: "アントニオロ",
	"Bartolo Mascarello": "バルトロ・マスカレッロ",
	Bava: "バーヴァ",
	Bersano: "ベルサーノ",
	Braida: "ブライダ",
	Broglia: "ブロリア",
	"Bruno Giacosa": "ブルーノ・ジャコーザ",
	"Bruno Rocca": "ブルーノ・ロッカ",
	"Ca' del Baio": "カ・デル・バイオ",
	"Cascina Bruciata": "カッシーナ・ブルチャータ",
	"Cascina delle Rose": "カッシーナ・デッレ・ローゼ",
	"Castellari Bergaglio": "カステッラーリ・ベルガリオ",
	"Castello di Verduno": "カステッロ・ディ・ヴェルドゥーノ",
	Cavallotto: "カヴァロット",
	Ceretto: "チェレット",
	Chionetti: "キオネッティ",
	Cieck: "チエック",
	"Claudio Alario": "クラウディオ・アラリオ",
	"Claudio Mariotto": "クラウディオ・マリオット",
	"Colombera & Garella": "コロンベーラ・エ・ガレッラ",
	Coppo: "コッポ",
	"Domenico Clerico": "ドメニコ・クレリコ",
	"Elio Grasso": "エリオ・グラッソ",
	"Enrico Serafino": "エンリコ・セラフィーノ",
	"Ettore Germano": "エットーレ・ジェルマーノ",
	Ferrando: "フェランド",
	"Ferraris Agricola": "フェラーリス・アグリコラ",
	Fontanafredda: "フォンタナフレッダ",
	"Fratelli Alessandria": "フラテッリ・アレッサンドリア",
	"G.B. Burlotto": "ブルロット",
	"G.D. Vajra": "ヴァイラ",
	Gaja: "ガヤ",
	"Giacomo Conterno": "ジャコモ・コンテルノ",
	"La Gironda": "ラ・ジロンダ",
	"La Guardia": "ラ・グアルディア",
	"La Scolca": "ラ・スコルカ",
	"La Spinetta": "ラ・スピネッタ",
	"Luciano Sandrone": "ルチアーノ・サンドローネ",
	"Luigi Spertino": "ルイジ・スペルティーノ",
	Malvirà: "マルヴィラ",
	Marcarini: "マルカリーニ",
	Marenco: "マレンコ",
	"Marziano Abbona": "マルツィアーノ・アッボーナ",
	Massolino: "マッソリーノ",
	"Matteo Correggia": "マッテオ・コレッジア",
	"Michele Chiarlo": "ミケーレ・キアルロ",
	"Monchiero Carbone": "モンキエロ・カルボーネ",
	Montalbera: "モンタルベーラ",
	"Nervi-Conterno": "ネルヴィ・コンテルノ",
	"Nicola Bergaglio": "ニコラ・ベルガリオ",
	"Odilio Antoniotti": "オディリオ・アントニオッティ",
	Orsolani: "オルソラーニ",
	"Paolo Saracco": "パオロ・サラッコ",
	"Paolo Scavino": "パオロ・スカヴィーノ",
	Pecchenino: "ペッケニーノ",
	Pescaja: "ペスカイア",
	"Pico Maccario": "ピコ・マッカリオ",
	"Pio Cesare": "ピオ・チェザーレ",
	"Poderi Aldo Conterno": "アルド・コンテルノ",
	"Produttori del Barbaresco": "プロドゥットーリ・デル・バルバレスコ",
	"Proprietà Sperino": "プロプリエタ・スペリーノ",
	Roagna: "ロアーニャ",
	"Roberto Voerzio": "ロベルト・ヴォエルツィオ",
	Rovellotti: "ロヴェロッティ",
	"San Fereolo": "サン・フェレオロ",
	Sella: "セッラ",
	Sottimano: "ソッティマーノ",
	Tacchino: "タッキーノ",
	"Tenuta La Tenaglia": "テヌータ・ラ・テナリア",
	"Tenuta Tamburnin": "テヌータ・タンブルニン",
	"Torraccia del Piantavigna": "トッラッチャ・デル・ピアンタヴィーニャ",
	Travaglini: "トラヴァリーニ",
	Vietti: "ヴィエッティ",
	"Vigneti Massa": "ヴィニェティ・マッサ",
	"Villa Sparina": "ヴィッラ・スパリーナ",
	// トスカーナ
	Acquabona: "アクアボーナ",
	Argentiera: "アルジェンティエラ",
	Avignonesi: "アヴィニョネージ",
	"Badia a Coltibuono": "バディア・ア・コルティブオーノ",
	Banfi: "バンフィ",
	"Barone Ricasoli": "バローネ・リカーゾリ",
	"Biondi-Santi": "ビオンディ・サンティ",
	Boscarelli: "ボスカレッリ",
	Bruni: "ブルーニ",
	"Canalicchio di Sopra": "カナリッキオ・ディ・ソプラ",
	Capitoni: "カピトーニ",
	Carmignani: "カルミニャーニ",
	"Casanova di Neri": "カサノヴァ・ディ・ネリ",
	"Castello Banfi": "カステッロ・バンフィ",
	"Castello di Ama": "カステッロ・ディ・アマ",
	"Castello di Monsanto": "カステッロ・ディ・モンサント",
	"Castello di Volpaia": "カステッロ・ディ・ヴォルパイア",
	Cecilia: "チェチリア",
	Cerbaiona: "チェルバイオーナ",
	Cima: "チーマ",
	"Col d'Orcia": "コル・ドルチャ",
	ColleMassari: "コッレマッサーリ",
	Costanti: "コスタンティ",
	"Donatella Cinelli Colombini": "ドナテッラ・チネッリ・コロンビーニ",
	"Fattoria Ambra": "ファットリア・アンブラ",
	"Fattoria Le Pupille": "ファットリア・レ・プピッレ",
	"Fattoria del Buonamico": "ファットリア・デル・ブオナミーコ",
	"Fattoria di Fubbiano": "ファットリア・ディ・フッビアーノ",
	Fontodi: "フォントディ",
	Frescobaldi: "フレスコバルディ",
	Fuligni: "フリーニ",
	Fèlsina: "フェルシナ",
	Grattamacco: "グラッタマッコ",
	"Guado al Tasso": "グアド・アル・タッソ",
	"Gualdo del Re": "グアルド・デル・レ",
	"Il Colombaio di Santa Chiara": "イル・コロンバイオ・ディ・サンタ・キアラ",
	"Il Poggione": "イル・ポッジョーネ",
	"Isole e Olena": "イゾレ・エ・オレーナ",
	"Jacopo Banti": "ヤコポ・バンティ",
	"Le Macchiole": "レ・マッキオーレ",
	Lisini: "リジーニ",
	"Marchesi Antinori": "アンティノリ",
	Masseto: "マッセート",
	"Michele Satta": "ミケーレ・サッタ",
	Montenidoli: "モンテニドリ",
	Montevertine: "モンテヴェルティーネ",
	Ornellaia: "オルネライア",
	Panizzi: "パニッツィ",
	Petra: "ペトラ",
	Piaggia: "ピアッジャ",
	"Podere Sapaio": "ポデーレ・サパイオ",
	"Podere Scurtarola": "ポデーレ・スクルタローラ",
	"Poggio Argentiera": "ポッジョ・アルジェンティエラ",
	"Poggio di Sotto": "ポッジョ・ディ・ソット",
	Poliziano: "ポリツィアーノ",
	Querciabella: "クエルチャベッラ",
	Riecine: "リエチーネ",
	"Rocca delle Macìe": "ロッカ・デッレ・マチエ",
	"Rocca di Frassinello": "ロッカ・ディ・フラッシネッロ",
	Ruffino: "ルフィーノ",
	Salustri: "サルストリ",
	Salvioni: "サルヴィオーニ",
	"San Felice": "サン・フェリーチェ",
	"San Giusto a Rentennano": "サン・ジュスト・ア・レンテンナーノ",
	"Siro Pacenti": "シーロ・パチェンティ",
	Soldera: "ソルデラ",
	"Stefano Amerighi": "ステファノ・アメリギ",
	"Tenimenti Luigi d'Alessandro": "テニメンティ・ルイジ・ダレッサンドロ",
	"Tenuta San Guido": "テヌータ・サン・グイド",
	"Tenuta di Artimino": "テヌータ・ディ・アルティミーノ",
	"Tenuta di Capezzana": "テヌータ・ディ・カペッツァーナ",
	"Tenuta di Valgiano": "テヌータ・ディ・ヴァルジャーノ",
	Teruzzi: "テルッツィ",
	"Tua Rita": "トゥア・リータ",
	Valdicava: "ヴァルディカーヴァ",
	// ローヌ(#225 で全生産者ぶんを整備。北ローヌ・南ローヌ・周辺を通してカタカナ表記を持つ)
	"Alain Graillot": "アラン・グライヨ",
	"Alain Voge": "アラン・ヴォージュ",
	"Auguste Clape": "オーギュスト・クラープ",
	"Balma Venitia": "バルマ・ヴェニシア",
	"Cave La Suzienne": "カーヴ・ラ・シュジエンヌ",
	"Cave de Die Jaillance": "ジャイヤンス",
	"Cave de Tain": "カーヴ・ド・タン",
	"Caves Carod": "カロッド",
	"Château Courac": "シャトー・クーラック",
	"Château Fortia": "シャトー・フォルティア",
	"Château La Canorgue": "シャトー・ラ・カノルグ",
	"Château La Nerthe": "シャトー・ラ・ネルト",
	"Château Mont-Redon": "シャトー・モン・ルドン",
	"Château Mourgues du Grès": "シャトー・ムルグ・デュ・グレ",
	"Château Pesquié": "シャトー・ペスキエ",
	"Château Rayas": "シャトー・ラヤス",
	"Château Redortier": "シャトー・ルドルティエ",
	"Château Saint-Maurice": "シャトー・サン・モーリス",
	"Château Saint-Roch": "シャトー・サン・ロック",
	"Château Unang": "シャトー・ユナン",
	"Château Val Joanis": "シャトー・ヴァル・ジョアニス",
	"Château d'Aquéria": "シャトー・ダケリア",
	"Château d'Or et de Gueules": "シャトー・ドール・エ・ド・グール",
	"Château de Beaucastel": "シャトー・ド・ボーカステル",
	"Château de Montfaucon": "シャトー・ド・モンフォーコン",
	"Château de Montmirail": "シャトー・ド・モンミライユ",
	"Château de Nages": "シャトー・ド・ナージュ",
	"Château de Régusse": "シャトー・ド・レギュス",
	"Château de Saint Cosme": "シャトー・ド・サン・コム",
	"Château de Ségriès": "シャトー・ド・セグリエス",
	"Château de Trinquevedel": "シャトー・ド・トランクヴデル",
	"Château de la Gardine": "シャトー・ド・ラ・ガルディーヌ",
	"Château des Tours": "シャトー・デ・トゥール",
	"Château-Grillet": "シャトー・グリエ",
	"Clos Saint-Jean": "クロ・サン・ジャン",
	"Clos des Boutes": "クロ・デ・ブート",
	"Clos des Papes": "クロ・デ・パプ",
	"Clos du Mont-Olivet": "クロ・デュ・モン・オリヴェ",
	"Delas Frères": "デラス",
	"Domaine Achard-Vincent": "アシャール・ヴァンサン",
	"Domaine Alary": "ドメーヌ・アラリー",
	"Domaine André Perret": "アンドレ・ペレ",
	"Domaine Belle": "ドメーヌ・ベル",
	"Domaine Bernard Gripa": "ベルナール・グリパ",
	"Domaine Bernard Levet": "ベルナール・ルヴェ",
	"Domaine Brusset": "ドメーヌ・ブリュセ",
	"Domaine Chaboud-Cellier": "シャブー",
	"Domaine Charvin": "ドメーヌ・シャルヴァン",
	"Domaine Chaume-Arnaud": "ショーム・アルノー",
	"Domaine Christophe Pichon": "クリストフ・ピション",
	"Domaine Clusel-Roch": "クリュゼル・ロッシュ",
	"Domaine Combier": "ドメーヌ・コンビエ",
	"Domaine Courbis": "ドメーヌ・クルビス",
	"Domaine Coursodon": "クルソドン",
	"Domaine Elodie Balme": "エロディ・バルム",
	"Domaine Emmanuel Darnaud": "エマニュエル・ダルノー",
	"Domaine Faury": "ドメーヌ・フォーリー",
	"Domaine Franck Balthazar": "フランク・バルタザール",
	"Domaine François Villard": "フランソワ・ヴィラール",
	"Domaine Gallety": "ドメーヌ・ガレティ",
	"Domaine Henri Bonneau": "アンリ・ボノー",
	"Domaine Jamet": "ドメーヌ・ジャメ",
	"Domaine Jaume": "ドメーヌ・ジョーム",
	"Domaine Jean-Michel Gerin": "ジャン・ミシェル・ジェラン",
	"Domaine La Blaque": "ドメーヌ・ラ・ブラック",
	"Domaine La Bouïssière": "ラ・ブイシエール",
	"Domaine La Garrigue": "ドメーヌ・ラ・ギャリーグ",
	"Domaine La Monardière": "ラ・モナルディエール",
	"Domaine La Soumade": "ラ・スマード",
	"Domaine Lafond Roc-Epine": "ラフォン・ロック・エピーヌ",
	"Domaine Le Sang des Cailloux": "サン・デ・カイユー",
	"Domaine Les Goubert": "レ・グーベール",
	"Domaine Les Hautes Cances": "レ・オート・カンス",
	"Domaine Les Pallières": "レ・パリエール",
	"Domaine Maby": "ドメーヌ・マビー",
	"Domaine Marc Sorrel": "マルク・ソレル",
	"Domaine Oratoire Saint-Martin": "オラトワール・サン・マルタン",
	"Domaine Pierre Gaillard": "ピエール・ガイヤール",
	"Domaine Pierre Gonon": "ピエール・ゴノン",
	"Domaine Pélaquié": "ドメーヌ・ペラキエ",
	"Domaine Rabasse Charavin": "ラバス・シャラヴァン",
	"Domaine Raspail-Ay": "ラスパイユ・アイ",
	"Domaine Roger Sabon": "ロジェ・サボン",
	"Domaine Saint-Amant": "ドメーヌ・サン・タマン",
	"Domaine Saint-Luc": "ドメーヌ・サン・リュック",
	"Domaine Santa Duc": "サンタ・デュック",
	"Domaine Stéphane Ogier": "ステファン・オジエ",
	"Domaine Yves Gangloff": "イヴ・ガングロフ",
	"Domaine de Beaurenard": "ドメーヌ・ド・ボールナール",
	"Domaine de Cassan": "ドメーヌ・ド・カッサン",
	"Domaine de Coyeux": "ドメーヌ・ド・コワユー",
	"Domaine de Durban": "ドメーヌ・ド・デュルバン",
	"Domaine de Fenouillet": "ドメーヌ・ド・フヌイエ",
	"Domaine de Fondrèche": "ドメーヌ・ド・フォンドレッシュ",
	"Domaine de Grangeneuve": "ドメーヌ・ド・グランジュヌーヴ",
	"Domaine de Marcoux": "ドメーヌ・ド・マルクー",
	"Domaine de Maupas": "ドメーヌ・ド・モーパ",
	"Domaine de Montine": "ドメーヌ・ド・モンティーヌ",
	"Domaine de Montvac": "ドメーヌ・ド・モンヴァック",
	"Domaine de la Citadelle": "ドメーヌ・ド・ラ・シタデル",
	"Domaine de la Janasse": "ドメーヌ・ド・ラ・ジャナス",
	"Domaine de la Mordorée": "ラ・モルドレ",
	"Domaine de la Réméjeanne": "ラ・レメジャンヌ",
	"Domaine des Amouriers": "ドメーヌ・デ・ザムリエ",
	"Domaine des Bernardins": "ドメーヌ・デ・ベルナルダン",
	"Domaine des Escaravailles": "エスカラヴァイユ",
	"Domaine des Lises": "ドメーヌ・デ・リーズ",
	"Domaine des Rémizières": "レミジエール",
	"Domaine du Belvezet": "ドメーヌ・デュ・ベルヴゼ",
	"Domaine du Cayron": "ドメーヌ・デュ・カイロン",
	"Domaine du Coulet": "ドメーヌ・デュ・クーレ",
	"Domaine du Grapillon d'Or": "グラピヨン・ドール",
	"Domaine du Moulin": "ドメーヌ・デュ・ムーラン",
	"Domaine du Pégaü": "ドメーヌ・デュ・ペゴー",
	"Domaine du Trapadis": "ドメーヌ・デュ・トラパディス",
	"Domaine du Tunnel": "ドメーヌ・デュ・チュネル",
	"Domaine du Vieux Télégraphe": "ヴュー・テレグラフ",
	"E. Guigal": "ギガル",
	"Ferraton Père & Fils": "フェラトン",
	"Georges Vernay": "ジョルジュ・ヴェルネ",
	"Guillaume Gilles": "ギヨーム・ジル",
	"Jean-Claude Raspail": "ジャン・クロード・ラスパイユ",
	"Jean-Louis Chave": "ジャン・ルイ・シャーヴ",
	"La Vinsobraise": "ラ・ヴァンソブレーズ",
	"Le Vieux Donjon": "ル・ヴュー・ドンジョン",
	"Les Vignerons Créateurs": "レ・ヴィニュロン・クレアトゥール",
	"M. Chapoutier": "シャプティエ",
	"Marcel Richaud": "マルセル・リショー",
	"Mas Carlot": "マス・カルロ",
	"Paul Jaboulet Aîné": "ポール・ジャブレ・エネ",
	"Perrin & Fils": "ペラン",
	"Petra Viridis": "ペトラ・ヴィリディス",
	"Prieuré de Montézargues": "プリューレ・ド・モンテザルグ",
	"René Rostaing": "ルネ・ロスタン",
	"Terre des Chardons": "テール・デ・シャルドン",
	"Thierry Allemand": "ティエリー・アルマン",
	"Vidal-Fleury": "ヴィダル・フルーリー",
	"Vignerons Ardéchois": "ヴィニュロン・アルデシュワ",
	"Vincent Paris": "ヴァンサン・パリス",
	"Yves Cuilleron": "イヴ・キュイユロン",
	// ボージョレ(#228 で全生産者ぶんを整備。Georges Duboeuf は上のブルゴーニュ枠に既出)
	"Cave du Château de Chénas": "シャトー・ド・シェナ",
	"Charly Thévenet": "シャルリー・テヴネ",
	"Château Bonnet": "シャトー・ボネ",
	"Château Thivin": "シャトー・ティヴァン",
	"Château de Juliénas": "シャトー・ド・ジュリエナ",
	"Château de Pierreux": "シャトー・ド・ピエルー",
	"Château de Poncié": "シャトー・ド・ポンシエ",
	"Château de Raousset": "シャトー・ド・ラウセ",
	"Château de la Chaize": "シャトー・ド・ラ・シェーズ",
	"Château des Jacques": "シャトー・デ・ジャック",
	"Château des Ravatys": "シャトー・デ・ラヴァティ",
	"Château du Moulin-à-Vent": "シャトー・デュ・ムーラン・ナ・ヴァン",
	"Clos de la Roilette": "クロ・ド・ラ・ロワレット",
	"Damien Coquelet": "ダミアン・コクレ",
	"Domaine Chardigny": "ドメーヌ・シャルディニー",
	"Domaine Chevalier-Métrat": "シュヴァリエ・メトラ",
	"Domaine Chignard": "ドメーヌ・シニャール",
	"Domaine Diochon": "ドメーヌ・ディオション",
	"Domaine Dupeuble": "ドメーヌ・デュプブル",
	"Domaine Georges Descombes": "ジョルジュ・デコンブ",
	"Domaine JG Chasselay": "シャスレイ",
	"Domaine Jean-Claude Lapalu": "ジャン・クロード・ラパリュ",
	"Domaine Labruyère": "ドメーヌ・ラブリュイエール",
	"Domaine Laurent Martray": "ローラン・マルトレイ",
	"Domaine Louis-Claude Desvignes": "ルイ・クロード・デヴィーニュ",
	"Domaine Nicole Chanrion": "ニコル・シャンリオン",
	"Domaine Pascal et Jean-Philippe Granger": "パスカル・グランジェ",
	"Domaine Paul Janin et Fils": "ポール・ジャナン",
	"Domaine Richard Rottiers": "リシャール・ロティエ",
	"Domaine Rochette": "ドメーヌ・ロシェット",
	"Domaine Ruet": "ドメーヌ・リュエ",
	"Domaine Thillardon": "ティヤルドン",
	"Domaine de Chênepierre": "シェーヌピエール",
	"Domaine de Vernus": "ドメーヌ・ド・ヴェルニュス",
	"Domaine de la Grosse Pierre": "ラ・グロス・ピエール",
	"Domaine de la Madone": "ドメーヌ・ド・ラ・マドンヌ",
	"Domaine de la Vieille Église": "ラ・ヴィエイユ・エグリーズ",
	"Domaine des Billards": "ドメーヌ・デ・ビヤール",
	"Domaine des Duc": "ドメーヌ・デ・デュック",
	"Domaine des Marrans": "ドメーヌ・デ・マラン",
	"Domaine des Pierres": "ドメーヌ・デ・ピエール",
	"Domaine des Terres Dorées": "テール・ドレ",
	"Domaine du Clos du Fief": "クロ・デュ・フィエフ",
	"Domaine du Paradis": "ドメーヌ・デュ・パラディ",
	"Domaine Émile Cheysson": "エミール・シェイソン",
	"Domaines Chermette": "シェルメット",
	"Domaines Perrachon et Fils": "ペラション",
	"Domaines Piron": "ドメーヌ・ピロン",
	"Guy Breton": "ギィ・ブルトン",
	"Jean Foillard": "ジャン・フォイヤール",
	"Jean-Marc Burgaud": "ジャン・マルク・ビュルゴー",
	"Jean-Paul Thévenet": "ジャン・ポール・テヴネ",
	"Julien Sunier": "ジュリアン・スニエ",
	"Les Roches Bleues": "レ・ロッシュ・ブルー",
	"Maison Coquard": "メゾン・コカール",
	"Marcel Lapierre": "マルセル・ラピエール",
	"Yvon Métras": "イヴォン・メトラ",
	// アルザス(#227 で全生産者ぶんを整備。51のグラン・クリュに直接ぶら下がる造り手を通してカタカナ表記を持つ)
	"Albert Boxler": "アルベール・ボクスレー",
	"Albert Mann": "アルベール・マン",
	"Albert Seltz": "アルベール・セルツ",
	"Allimant-Laugner": "アリマン・ローニェ",
	"André Kientzler": "アンドレ・キンツレール",
	"Arthur Metz": "アルチュール・メッツ",
	"Barmès-Buecher": "バルメス・ビュシェール",
	"Bernard Weber": "ベルナール・ウェベール",
	Bestheim: "ベストハイム",
	"Bott-Geyl": "ボット・ゲイル",
	"Bruno Sorg": "ブルーノ・ソルグ",
	"Cave de Beblenheim": "カーヴ・ド・ベブレンハイム",
	"Cave de Hunawihr": "カーヴ・ド・ユナヴィール",
	"Cave de Pfaffenheim": "カーヴ・ド・プファッフェンハイム",
	"Cave de Ribeauvillé": "カーヴ・ド・リボーヴィレ",
	"Cave de Turckheim": "カーヴ・ド・チュルクハイム",
	"Cave du Vieil Armand": "カーヴ・デュ・ヴィエイユ・アルマン",
	"Cave Jean Geiler": "ジャン・ガイラー",
	"Charles Baur": "シャルル・バウアー",
	"Charles Koehly": "シャルル・ケーリー",
	"Château Ollwiller": "シャトー・オルヴィレール",
	"Dirler-Cadé": "ディルレール・カデ",
	"Domaine Bechtold": "ドメーヌ・ベヒトルド",
	"Domaine Boeckel": "ドメーヌ・ベッケル",
	"Domaine Engel": "ドメーヌ・エンゲル",
	"Domaine Gilg": "ドメーヌ・ギルグ",
	"Domaine Hering": "ドメーヌ・ヘリング",
	"Domaine Julien Meyer": "ドメーヌ・ジュリアン・メイエー",
	"Domaine Lissner": "ドメーヌ・リスネール",
	"Domaine Loew": "ドメーヌ・ロエヴ",
	"Domaine Moltes": "ドメーヌ・モルテス",
	"Domaine Muhlberger": "ドメーヌ・ミュールベルジェ",
	"Domaine Ostertag": "ドメーヌ・オステルタッグ",
	"Domaine Pfister": "ドメーヌ・プフィステール",
	"Domaine Rémy Gresser": "ドメーヌ・レミ・グレッセール",
	"Domaine Rieffel": "ドメーヌ・リーフェル",
	"Domaine Rieflé-Landmann": "ドメーヌ・リフレ・ラントマン",
	"Domaine Ruhlmann": "ドメーヌ・ルルマン",
	"Domaine Schaeffer-Woerly": "ドメーヌ・シェフェール・ウェルリー",
	"Domaine Schoffit": "ドメーヌ・ショフィット",
	"Domaine Sipp Mack": "ドメーヌ・シップ・マック",
	"Domaine Stoeffler": "ドメーヌ・ストフレール",
	"Domaine Straub": "ドメーヌ・ストローブ",
	"Domaine Wach": "ドメーヌ・ヴァック",
	"Domaine Weinbach": "ドメーヌ・ヴァインバック",
	"Domaine Zind-Humbrecht": "ドメーヌ・ツィント・フンブレヒト",
	"Domaines Schlumberger": "ドメーヌ・シュルンベルジェ",
	"Dopff au Moulin": "ドップ・オ・ムーラン",
	"Emile Beyer": "エミール・バイヤー",
	"Ernest Burn": "エルネスト・ビュルン",
	"Frédéric Mallo": "フレデリック・マロ",
	"Frédéric Mochel": "フレデリック・モシェル",
	"Frey-Sohler": "フレイ・ゾレール",
	"Gérard Neumeyer": "ジェラール・ノイマイヤー",
	"Gustave Lorentz": "ギュスターヴ・ロレンツ",
	"Hubert Metz": "ユベール・メッツ",
	Hugel: "ヒューゲル",
	"Jean Becker": "ジャン・ベッケール",
	"Jean Sipp": "ジャン・シップ",
	"Jean-Baptiste Adam": "ジャン・バティスト・アダム",
	"Jean-Marc Bernhard": "ジャン・マルク・ベルナール",
	"Joseph Cattin": "ジョセフ・カッタン",
	Josmeyer: "ジョスメイヤー",
	Klipfel: "クリップフェル",
	"Koeberlé-Kreyer": "ケベルレ・クレイエール",
	"Kuentz-Bas": "クンツ・バス",
	"Léon Beyer": "レオン・ベイエ",
	"Léon Boesch": "レオン・ベッシュ",
	"Louis Sipp": "ルイ・シップ",
	"Lucien Albrecht": "リュシアン・アルブレヒト",
	"Marc Kreydenweiss": "マルク・クライデンヴァイス",
	"Marc Tempé": "マルク・タンペ",
	"Marcel Deiss": "マルセル・ダイス",
	"Meyer-Fonné": "メイエー・フォネ",
	"Mittnacht Frères": "ミットナット・フレール",
	"Paul Blanck": "ポール・ブランク",
	"Paul Ginglinger": "ポール・ジャングランジェ",
	"Pierre Frick": "ピエール・フリック",
	"Pierre Sparr": "ピエール・スパー",
	"René Muré": "ルネ・ミュレ",
	"Roland Schmitt": "ロラン・シュミット",
	"Romain Fritsch": "ロマン・フリッチュ",
	"Sick-Dreyer": "シック・ドレイエール",
	"Sylvie Spielmann": "シルヴィ・シュピールマン",
	"Théo Cattin": "テオ・カッタン",
	Trimbach: "トリンバック",
	"Valentin Zusslin": "ヴァランタン・ズスラン",
	Wolfberger: "ヴォルフベルジェ",
	"Wunsch & Mann": "ヴュンシュ・エ・マン",
};

export interface PurchaseLinks {
	rakuten: string;
	amazon: string;
}

/**
 * 「ジロンド県内の多数の生産者」のような、実在の単一生産者を指さない
 * プレースホルダー表記はリンク対象外にする。
 */
export function isLinkableProducerName(name: string): boolean {
	return name !== "-" && !name.includes("多数の");
}

/** 楽天市場のワインジャンル内検索URL。IDが設定されていればアフィリエイトリンクでラップ */
export function buildRakutenSearchUrl(
	keyword: string,
	affiliateId = "",
): string {
	const searchUrl = `https://search.rakuten.co.jp/search/mall/${encodeURIComponent(keyword)}/${RAKUTEN_WINE_GENRE_ID}/`;
	if (!affiliateId) return searchUrl;
	const encoded = encodeURIComponent(searchUrl);
	return `https://hb.afl.rakuten.co.jp/hgc/${affiliateId}/?pc=${encoded}&m=${encoded}`;
}

/** Amazon.co.jp の検索URL。IDが設定されていればもしもアフィリエイト経由でラップ */
export function buildAmazonSearchUrl(keyword: string, moshimoAId = ""): string {
	const searchUrl = `https://www.amazon.co.jp/s?k=${encodeURIComponent(keyword)}`;
	if (!moshimoAId) return searchUrl;
	return `https://af.moshimo.com/af/c/click?a_id=${moshimoAId}&${MOSHIMO_AMAZON_PARAMS}&url=${encodeURIComponent(searchUrl)}`;
}

/**
 * 生産者1件分の購入リンク。手動リンク(links)があればそれを優先し、
 * なければ searchKeyword → 共通辞書 → name の順のキーワードで検索リンクを生成する。
 * プレースホルダー表記の生産者には null を返す。
 * winery(シャトー)の producers は所有者/運営体なので、呼び出し側でリンクを
 * 出さない判断をすること(代わりに getWineryPurchaseLinks を使う)。
 */
export function getProducerPurchaseLinks(
	producer: AopProducer,
	config: AffiliateConfig = EMPTY_AFFILIATE_CONFIG,
): PurchaseLinks | null {
	if (!isLinkableProducerName(producer.name)) return null;
	const keyword =
		producer.searchKeyword ??
		PRODUCER_SEARCH_KEYWORDS[producer.name] ??
		producer.name;
	return {
		rakuten:
			producer.links?.rakuten ?? buildRakutenSearchUrl(keyword, config.rakuten),
		amazon:
			producer.links?.amazon ??
			buildAmazonSearchUrl(keyword, config.moshimoAmazon),
	};
}

/**
 * winery(ボルドーのシャトー等)はAOPエントリ自体が生産者なので、
 * シャトー名(nameJa)で検索する購入リンクを返す。winery 以外は null。
 */
export function getWineryPurchaseLinks(
	aop: Aop,
	config: AffiliateConfig = EMPTY_AFFILIATE_CONFIG,
): PurchaseLinks | null {
	if (aop.kind !== "winery") return null;
	return {
		rakuten: buildRakutenSearchUrl(aop.nameJa, config.rakuten),
		amazon: buildAmazonSearchUrl(aop.nameJa, config.moshimoAmazon),
	};
}
